In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
cn = pd.read_csv('E:\Data Science Dataset\Final project datasets\cancer.csv')

In [5]:
cn.head(20)

,index,Patient Id,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,...,Fatigue,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold,Dry Cough,Snoring,Level
0,0,P1,33,1,2,4,5,4,3,2,...,3,4,2,2,3,1,2,3,4,Low
1,1,P10,17,1,3,1,5,3,4,2,...,1,3,7,8,6,2,1,7,2,Medium
2,2,P100,35,1,4,5,6,5,5,4,...,8,7,9,2,1,4,6,7,2,High
3,3,P1000,37,1,7,7,7,7,6,7,...,4,2,3,1,4,5,6,7,5,High
4,4,P101,46,1,6,8,7,7,7,6,...,3,2,4,1,4,2,4,2,3,High
5,5,P102,35,1,4,5,6,5,5,4,...,8,7,9,2,1,4,6,7,2,High
6,6,P103,52,2,2,4,5,4,3,2,...,3,4,2,2,3,1,2,3,4,Low
7,7,P104,28,2,3,1,4,3,2,3,...,3,2,2,4,2,2,3,4,3,Low
8,8,P105,35,2,4,5,6,5,6,5,...,1,4,3,2,4,6,2,4,1,Medium
9,9,P106,46,1,2,3,4,2,4,3,...,1,2,4,6,5,4,2,1,5,Medium
10,10,P107,44,1,6,7,7,7,7,6,...,5,3,2,7,8,2,4,5,3,High
11,11,P108,64,2,6,8,7,7,7,6,...,9,6,5,7,2,4,3,1,4,High
12,12,P109,39,2,4,5,6,6,5,4,...,5,3,2,4,3,1,7,5,6,Medium
13,13,P11,34,1,6,7,7,7,6,7,...,4,2,3,1,4,5,6,7,5,High
14,14,P110,27,2,3,1,4,2,3,2,...,2,2,3,4,1,5,2,6,2,Low
15,15,P111,73,1,5,6,6,5,6,5,...,4,3,6,2,1,2,1,6,2,Medium
16,16,P112,17,1,3,1,5,3,4,2,...,1,3,7,8,6,2,1,7,2,Medium
17,17,P113,34,1,6,7,7,7,6,7,...,4,2,3,1,4,5,6,7,5,High
18,18,P114,36,1,6,7,7,7,7,7,...,8,5,7,6,7,8,7,6,2,High
19,19,P115,14,1,2,4,5,6,5,5,...,5,3,2,1,4,7,2,1,6,Medium

In [6]:
cn.isnull().sum()

index                       0
Patient Id                  0
Age                         0
Gender                      0
Air Pollution               0
Alcohol use                 0
Dust Allergy                0
OccuPational Hazards        0
Genetic Risk                0
chronic Lung Disease        0
Balanced Diet               0
Obesity                     0
Smoking                     0
Passive Smoker              0
Chest Pain                  0
Coughing of Blood           0
Fatigue                     0
Weight Loss                 0
Shortness of Breath         0
Wheezing                    0
Swallowing Difficulty       0
Clubbing of Finger Nails    0
Frequent Cold               0
Dry Cough                   0
Snoring                     0
Level                       0
dtype: int64

In [7]:
cn1 = cn

In [8]:
cn = cn.iloc[:, 1:]

In [9]:
cn.head()

,Patient Id,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,Balanced Diet,...,Fatigue,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold,Dry Cough,Snoring,Level
0,P1,33,1,2,4,5,4,3,2,2,...,3,4,2,2,3,1,2,3,4,Low
1,P10,17,1,3,1,5,3,4,2,2,...,1,3,7,8,6,2,1,7,2,Medium
2,P100,35,1,4,5,6,5,5,4,6,...,8,7,9,2,1,4,6,7,2,High
3,P1000,37,1,7,7,7,7,6,7,7,...,4,2,3,1,4,5,6,7,5,High
4,P101,46,1,6,8,7,7,7,6,7,...,3,2,4,1,4,2,4,2,3,High

In [10]:
cn.select_dtypes('object')

    Patient Id   Level
0           P1     Low
1          P10  Medium
2         P100    High
3        P1000    High
4         P101    High
..         ...     ...
995       P995    High
996       P996    High
997       P997    High
998       P998    High
999       P999    High

[1000 rows x 2 columns]

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [12]:
cn[cn.select_dtypes(include = ['object']).columns] =cn[cn.select_dtypes(include = ['object']).columns].apply(le.fit_transform)

In [13]:
cn.select_dtypes('object')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[1000 rows x 0 columns]

In [14]:
cn.head()

,Patient Id,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,Balanced Diet,...,Fatigue,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold,Dry Cough,Snoring,Level
0,0,33,1,2,4,5,4,3,2,2,...,3,4,2,2,3,1,2,3,4,1
1,1,17,1,3,1,5,3,4,2,2,...,1,3,7,8,6,2,1,7,2,2
2,2,35,1,4,5,6,5,5,4,6,...,8,7,9,2,1,4,6,7,2,0
3,3,37,1,7,7,7,7,6,7,7,...,4,2,3,1,4,5,6,7,5,0
4,4,46,1,6,8,7,7,7,6,7,...,3,2,4,1,4,2,4,2,3,0

In [15]:
from sklearn.model_selection import train_test_split
cn_train, cn_test = train_test_split(cn, test_size = .2)

In [16]:
cn_train_x = cn_train.iloc[: , 0:-1]
cn_train_y = cn_train.iloc[: , -1]

In [17]:
cn_test_x = cn_test.iloc[: , 0:-1]
cn_test_y = cn_test.iloc[: , -1]

In [18]:
print(cn_train_x.shape)
print(cn_train_y.shape)
print()
print('-----------------------')
print()
print(cn_test_x.shape)
print(cn_test_y.shape)

(800, 24)
(800,)

-----------------------

(200, 24)
(200,)

In [19]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(multi_class='multinomial')

In [20]:
logreg.fit(cn_train_x, cn_train_y) # model created

C:\Users\rohin\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(multi_class='multinomial')

In [21]:
pred = logreg.predict(cn_test_x)

In [22]:
pred

array([2, 0, 1, 2, 2, 1, 2, 0, 2, 0, 1, 2, 0, 1, 1, 2, 2, 0, 2, 0, 1, 2,
       0, 0, 1, 2, 2, 2, 2, 2, 1, 2, 0, 2, 0, 2, 0, 0, 1, 1, 2, 2, 0, 1,
       1, 0, 0, 1, 0, 1, 2, 2, 2, 2, 0, 0, 2, 1, 0, 0, 0, 2, 1, 0, 0, 2,
       0, 2, 0, 0, 1, 0, 1, 0, 2, 2, 2, 1, 2, 2, 1, 2, 1, 1, 0, 2, 0, 2,
       0, 1, 0, 2, 0, 1, 2, 0, 1, 0, 1, 0, 2, 1, 2, 1, 1, 1, 0, 1, 2, 1,
       0, 2, 0, 2, 2, 2, 2, 0, 1, 2, 0, 2, 1, 0, 1, 2, 1, 2, 0, 0, 0, 1,
       0, 0, 2, 1, 0, 0, 2, 2, 1, 2, 0, 1, 0, 0, 2, 2, 2, 2, 2, 0, 2, 1,
       2, 2, 0, 0, 2, 2, 0, 2, 1, 1, 1, 1, 1, 2, 1, 0, 0, 0, 0, 0, 1, 2,
       0, 0, 1, 0, 1, 2, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 2, 1, 1, 1, 1,
       1, 0])

In [23]:
cn_test_y

241    2
891    0
486    1
144    1
67     2
      ..
499    1
164    1
829    1
386    1
899    0
Name: Level, Length: 200, dtype: int32

In [24]:
from sklearn.metrics import confusion_matrix

In [25]:
tab1 = confusion_matrix(pred, cn_test_y) 
tab1

array([[68,  2,  4],
       [ 0, 55,  1],
       [ 0, 10, 60]], dtype=int64)

In [26]:
tab2 = confusion_matrix(cn_test_y, pred)
tab2

array([[68,  0,  0],
       [ 2, 55, 10],
       [ 4,  1, 60]], dtype=int64)

In [27]:
tab1.diagonal().sum()

183

In [28]:
tab1.sum()

200

In [29]:
tab1.diagonal().sum() * 100 / tab1.sum()

91.5

In [30]:
from sklearn.metrics import accuracy_score

In [31]:
accuracy_score(cn_test_y, pred) * 100

91.5

In [32]:
from sklearn.metrics import recall_score

In [33]:
recall_score(pred, cn_test_y, average = 'weighted')

0.915

In [34]:
from sklearn.metrics import f1_score

In [36]:
f1_score(pred, cn_test_y, average = 'weighted')

0.9158838123592504

In [37]:
pred_prob = logreg.predict_proba(cn.iloc[:, 0:-1])
pred_prob

array([[1.95268131e-01, 1.65036836e-01, 6.39695033e-01],
       [2.28544403e-02, 9.22992425e-02, 8.84846317e-01],
       [9.95083538e-01, 2.36196319e-04, 4.68026618e-03],
       ...,
       [9.96792007e-01, 3.47872085e-04, 2.86012133e-03],
       [9.99760962e-01, 1.37952591e-04, 1.01085215e-04],
       [9.83596212e-01, 1.00532960e-02, 6.35049151e-03]])

In [38]:
type(pred_prob)

numpy.ndarray

In [39]:
pred_prob = pd.DataFrame(pred_prob)

In [40]:
pred_prob = pred_prob.rename(columns= {pred_prob.columns[0] : 'Prob0', pred_prob.columns[1] : 'Prob1'})

In [41]:
pred_prob

        Prob0     Prob1         2
0    0.195268  0.165037  0.639695
1    0.022854  0.092299  0.884846
2    0.995084  0.000236  0.004680
3    0.997813  0.001385  0.000802
4    0.996187  0.002874  0.000939
..        ...       ...       ...
995  0.881772  0.090150  0.028078
996  0.992953  0.000686  0.006361
997  0.996792  0.000348  0.002860
998  0.999761  0.000138  0.000101
999  0.983596  0.010053  0.006350

[1000 rows x 3 columns]

In [42]:
pred_prob = pd.concat([pred_prob, cn1.Level], axis = 1)

In [43]:
pred_prob.head()

      Prob0     Prob1         2   Level
0  0.195268  0.165037  0.639695     Low
1  0.022854  0.092299  0.884846  Medium
2  0.995084  0.000236  0.004680    High
3  0.997813  0.001385  0.000802    High
4  0.996187  0.002874  0.000939    High

In [44]:
pred_prob = pred_prob.sort_values('Prob1', ascending=False)

In [45]:
pred_prob

        Prob0     Prob1         2 Level
948  0.000245  0.999368  0.000387   Low
837  0.000303  0.999240  0.000457   Low
950  0.000300  0.999092  0.000608   Low
726  0.000374  0.999086  0.000540   Low
839  0.000370  0.998912  0.000718   Low
..        ...       ...       ...   ...
542  0.999125  0.000006  0.000869  High
431  0.999163  0.000005  0.000832  High
320  0.999199  0.000004  0.000797  High
209  0.999234  0.000003  0.000763  High
98   0.999267  0.000003  0.000730  High

[1000 rows x 4 columns]

In [46]:
pred_prob = pred_prob.iloc[:, [1,2]]

In [47]:
pred_prob

        Prob1         2
948  0.999368  0.000387
837  0.999240  0.000457
950  0.999092  0.000608
726  0.999086  0.000540
839  0.998912  0.000718
..        ...       ...
542  0.000006  0.000869
431  0.000005  0.000832
320  0.000004  0.000797
209  0.000003  0.000763
98   0.000003  0.000730

[1000 rows x 2 columns]

In [48]:
 greater_than_8 = pred_prob['Prob1'] > 0.8

In [49]:
greater_than_8

948     True
837     True
950     True
726     True
839     True
       ...
542    False
431    False
320    False
209    False
98     False
Name: Prob1, Length: 1000, dtype: bool

In [50]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()

In [52]:
dt.fit(cn_train_x, cn_train_y)

DecisionTreeClassifier()

In [53]:
pred = dt.predict(cn_test_x)

In [54]:
from sklearn.metrics import confusion_matrix

In [56]:
tab_dt = confusion_matrix(pred, cn_test_y)
tab_dt

array([[68,  0,  0],
       [ 0, 67,  0],
       [ 0,  0, 65]], dtype=int64)

In [57]:
tab_dt.diagonal().sum() * 100 / tab_dt.sum()

100.0

In [58]:
dt.feature_importances_

array([0.        , 0.        , 0.        , 0.07036508, 0.        ,
       0.        , 0.        , 0.01694891, 0.        , 0.        ,
       0.12210137, 0.        , 0.        , 0.        , 0.40068113,
       0.        , 0.        , 0.        , 0.25136846, 0.        ,
       0.02574566, 0.        , 0.        , 0.11278939])

In [60]:
feat_imp_df = pd.DataFrame({'Features' : cn_train_x.columns, 'Importance': dt.feature_importances_})
feat_imp_df

                    Features  Importance
0                 Patient Id    0.000000
1                        Age    0.000000
2                     Gender    0.000000
3              Air Pollution    0.070365
4                Alcohol use    0.000000
5               Dust Allergy    0.000000
6       OccuPational Hazards    0.000000
7               Genetic Risk    0.016949
8       chronic Lung Disease    0.000000
9              Balanced Diet    0.000000
10                   Obesity    0.122101
11                   Smoking    0.000000
12            Passive Smoker    0.000000
13                Chest Pain    0.000000
14         Coughing of Blood    0.400681
15                   Fatigue    0.000000
16               Weight Loss    0.000000
17       Shortness of Breath    0.000000
18                  Wheezing    0.251368
19     Swallowing Difficulty    0.000000
20  Clubbing of Finger Nails    0.025746
21             Frequent Cold    0.000000
22                 Dry Cough    0.000000
23                   Snoring    0.112789

In [61]:
feat_imp_df.sort_values('Importance', ascending=False)

                    Features  Importance
14         Coughing of Blood    0.400681
18                  Wheezing    0.251368
10                   Obesity    0.122101
23                   Snoring    0.112789
3              Air Pollution    0.070365
20  Clubbing of Finger Nails    0.025746
7               Genetic Risk    0.016949
22                 Dry Cough    0.000000
21             Frequent Cold    0.000000
19     Swallowing Difficulty    0.000000
17       Shortness of Breath    0.000000
16               Weight Loss    0.000000
15                   Fatigue    0.000000
0                 Patient Id    0.000000
13                Chest Pain    0.000000
1                        Age    0.000000
11                   Smoking    0.000000
9              Balanced Diet    0.000000
8       chronic Lung Disease    0.000000
6       OccuPational Hazards    0.000000
5               Dust Allergy    0.000000
4                Alcohol use    0.000000
2                     Gender    0.000000
12            Passive Smoker    0.000000

In [62]:
from IPython.display import Image
from sklearn.tree import export_graphviz
import pydotplus
import pydot
from IPython.display import Image
from six import StringIO
#this libraries will not support

ModuleNotFoundError: No module named 'pydotplus'

In [63]:
cn_train_x_names = cn_train_x.columns